// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/pad/proto/pad.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PadStatus represents the status of a pad, indicating whether it is active, expired, not found, or deleted. This status helps clients understand the current state of a pad when retrieving or managing it.
type PadStatus int32

const (
	PadStatus_ACTIVE    PadStatus = 0
	PadStatus_EXPIRED   PadStatus = 1
	PadStatus_NOT_FOUND PadStatus = 2
	PadStatus_DELETED   PadStatus = 3
)

// Enum value maps for PadStatus.
var (
	PadStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "EXPIRED",
		2: "NOT_FOUND",
		3: "DELETED",
	}
	PadStatus_value = map[string]int32{
		"ACTIVE":    0,
		"EXPIRED":   1,
		"NOT_FOUND": 2,
		"DELETED":   3,
	}
)

func (x PadStatus) Enum() *PadStatus {
	p := new(PadStatus)
	*p = x
	return p
}

func (x PadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pad_proto_pad_proto_enumTypes[0].Descriptor()
}

func (PadStatus) Type() protoreflect.EnumType {
	return &file_internal_pad_proto_pad_proto_enumTypes[0]
}

func (x PadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PadStatus.Descriptor instead.
func (PadStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_pad_proto_pad_proto_rawDescGZIP(), []int{0}
}

// PadRequest is used to retrieve or delete a pad by its unique ID. The optional API key can be included for authentication and authorization purposes, allowing the system to associate pads with specific users and enforce access controls.
type PadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // Optional API key for authentication and authorization purposes. This can be used to associate pads with specific users and enforce access controls.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PadRequest) Reset() {
	*x = PadRequest{}
	mi := &file_internal_pad_proto_pad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PadRequest) ProtoMessage() {}

func (x *PadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pad_proto_pad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PadRequest.ProtoReflect.Descriptor instead.
func (*PadRequest) Descriptor() ([]byte, []int) {
	return file_internal_pad_proto_pad_proto_rawDescGZIP(), []int{0}
}

func (x *PadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PadRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// PadResponse is returned when retrieving or deleting a pad. It includes the content of the pad, any associated metadata, and the status of the pad (active, expired, not found, or deleted). This information helps clients understand the current state of the pad and its content when performing operations on it.
type PadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content of the pad, which can be any binary data (e.g., text, images, etc.)
	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// Optional metadata for the pad, which can include any key-value pairs (e.g., author, creation date, etc.)
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The status of the pad, indicating whether it is active, expired, or not found.
	Status        PadStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pad.PadStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PadResponse) Reset() {
	*x = PadResponse{}
	mi := &file_internal_pad_proto_pad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PadResponse) ProtoMessage() {}

func (x *PadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pad_proto_pad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PadResponse.ProtoReflect.Descriptor instead.
func (*PadResponse) Descriptor() ([]byte, []int) {
	return file_internal_pad_proto_pad_proto_rawDescGZIP(), []int{1}
}

func (x *PadResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PadResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PadResponse) GetStatus() PadStatus {
	if x != nil {
		return x.Status
	}
	return PadStatus_ACTIVE
}

// CreatePadRequest is used to create a new pad with the specified content, TTL, and metadata. The response includes the unique ID of the created pad and its status.
type CreatePadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content of the pad, which can be any binary data (e.g., text, images, etc.)
	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// The time-to-live (TTL) for the pad in seconds. After this duration, the pad will be automatically deleted. 0 means no expiration.
	TtlSeconds uint32 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Optional metadata for the pad, which can include any key-value pairs (e.g., author, creation date, etc.)
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ApiKey        string            `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // Optional API key for authentication and authorization purposes. This can be used to associate pads with specific users and enforce access controls.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePadRequest) Reset() {
	*x = CreatePadRequest{}
	mi := &file_internal_pad_proto_pad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePadRequest) ProtoMessage() {}

func (x *CreatePadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pad_proto_pad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePadRequest.ProtoReflect.Descriptor instead.
func (*CreatePadRequest) Descriptor() ([]byte, []int) {
	return file_internal_pad_proto_pad_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePadRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CreatePadRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreatePadRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreatePadRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// CreatedPadResponse is returned when a pad is successfully created. It includes the unique ID of the created pad and its status.
type CreatedPadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        PadStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=pad.PadStatus" json:"status,omitempty"`
	ValidUntil    uint64                 `protobuf:"varint,3,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"` // Timestamp (in seconds since epoch) until which the pad is valid. 0 means no expiration.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedPadResponse) Reset() {
	*x = CreatedPadResponse{}
	mi := &file_internal_pad_proto_pad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedPadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedPadResponse) ProtoMessage() {}

func (x *CreatedPadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pad_proto_pad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedPadResponse.ProtoReflect.Descriptor instead.
func (*CreatedPadResponse) Descriptor() ([]byte, []int) {
	return file_internal_pad_proto_pad_proto_rawDescGZIP(), []int{3}
}

func (x *CreatedPadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatedPadResponse) GetStatus() PadStatus {
	if x != nil {
		return x.Status
	}
	return PadStatus_ACTIVE
}

func (x *CreatedPadResponse) GetValidUntil() uint64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

var File_internal_pad_proto_pad_proto protoreflect.FileDescriptor

const file_internal_pad_proto_pad_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/pad/proto/pad.proto\x12\x03pad\"5\n" +
	"\n" +
	"PadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\xc2\x01\n" +
	"\vPadResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12:\n" +
	"\bmetadata\x18\x02 \x03(\v2\x1e.pad.PadResponse.MetadataEntryR\bmetadata\x12&\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0e.pad.PadStatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\x10CreatePadRequest\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\rR\n" +
	"ttlSeconds\x12?\n" +
	"\bmetadata\x18\x03 \x03(\v2#.pad.CreatePadRequest.MetadataEntryR\bmetadata\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x12CreatedPadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.pad.PadStatusR\x06status\x12\x1f\n" +
	"\vvalid_until\x18\x03 \x01(\x04R\n" +
	"validUntil*@\n" +
	"\tPadStatus\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\v\n" +
	"\aEXPIRED\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\v\n" +
	"\aDELETED\x10\x032\xa6\x01\n" +
	"\n" +
	"PadService\x12;\n" +
	"\tCreatePad\x12\x15.pad.CreatePadRequest\x1a\x17.pad.CreatedPadResponse\x12+\n" +
	"\x06GetPad\x12\x0f.pad.PadRequest\x1a\x10.pad.PadResponse\x12.\n" +
	"\tDeletePad\x12\x0f.pad.PadRequest\x1a\x10.pad.PadResponseB0Z.github.com/guionardo/gs-dev/internal/pad/protob\x06proto3"

var (
	file_internal_pad_proto_pad_proto_rawDescOnce sync.Once
	file_internal_pad_proto_pad_proto_rawDescData []byte
)

func file_internal_pad_proto_pad_proto_rawDescGZIP() []byte {
	file_internal_pad_proto_pad_proto_rawDescOnce.Do(func() {
		file_internal_pad_proto_pad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pad_proto_pad_proto_rawDesc), len(file_internal_pad_proto_pad_proto_rawDesc)))
	})
	return file_internal_pad_proto_pad_proto_rawDescData
}

var file_internal_pad_proto_pad_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pad_proto_pad_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_pad_proto_pad_proto_goTypes = []any{
	(PadStatus)(0),             // 0: pad.PadStatus
	(*PadRequest)(nil),         // 1: pad.PadRequest
	(*PadResponse)(nil),        // 2: pad.PadResponse
	(*CreatePadRequest)(nil),   // 3: pad.CreatePadRequest
	(*CreatedPadResponse)(nil), // 4: pad.CreatedPadResponse
	nil,                        // 5: pad.PadResponse.MetadataEntry
	nil,                        // 6: pad.CreatePadRequest.MetadataEntry
}
var file_internal_pad_proto_pad_proto_depIdxs = []int32{
	5, // 0: pad.PadResponse.metadata:type_name -> pad.PadResponse.MetadataEntry
	0, // 1: pad.PadResponse.status:type_name -> pad.PadStatus
	6, // 2: pad.CreatePadRequest.metadata:type_name -> pad.CreatePadRequest.MetadataEntry
	0, // 3: pad.CreatedPadResponse.status:type_name -> pad.PadStatus
	3, // 4: pad.PadService.CreatePad:input_type -> pad.CreatePadRequest
	1, // 5: pad.PadService.GetPad:input_type -> pad.PadRequest
	1, // 6: pad.PadService.DeletePad:input_type -> pad.PadRequest
	4, // 7: pad.PadService.CreatePad:output_type -> pad.CreatedPadResponse
	2, // 8: pad.PadService.GetPad:output_type -> pad.PadResponse
	2, // 9: pad.PadService.DeletePad:output_type -> pad.PadResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_pad_proto_pad_proto_init() }
func file_internal_pad_proto_pad_proto_init() {
	if File_internal_pad_proto_pad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pad_proto_pad_proto_rawDesc), len(file_internal_pad_proto_pad_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pad_proto_pad_proto_goTypes,
		DependencyIndexes: file_internal_pad_proto_pad_proto_depIdxs,
		EnumInfos:         file_internal_pad_proto_pad_proto_enumTypes,
		MessageInfos:      file_internal_pad_proto_pad_proto_msgTypes,
	}.Build()
	File_internal_pad_proto_pad_proto = out.File
	file_internal_pad_proto_pad_proto_goTypes = nil
	file_internal_pad_proto_pad_proto_depIdxs = nil
}
