// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/pad/proto/pad.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PadService_CreatePad_FullMethodName = "/pad.PadService/CreatePad"
	PadService_GetPad_FullMethodName    = "/pad.PadService/GetPad"
	PadService_DeletePad_FullMethodName = "/pad.PadService/DeletePad"
)

// PadServiceClient is the client API for PadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PadService defines the gRPC service for managing pads, including creating, retrieving, and deleting pads. Each method corresponds to a specific operation on the pads, allowing clients to interact with the pad management system effectively.
type PadServiceClient interface {
	// CreatePad creates a new pad with the specified content, TTL, and metadata. The response includes the unique ID of the created pad and its status.
	CreatePad(ctx context.Context, in *CreatePadRequest, opts ...grpc.CallOption) (*CreatedPadResponse, error)
	// GetPad retrieves the content and metadata of a pad by its unique ID. The response includes the pad's body, metadata, and status.
	GetPad(ctx context.Context, in *PadRequest, opts ...grpc.CallOption) (*PadResponse, error)
	// DeletePad deletes a pad by its unique ID. The response indicates whether the pad was successfully deleted or if it was not found.
	DeletePad(ctx context.Context, in *PadRequest, opts ...grpc.CallOption) (*PadResponse, error)
}

type padServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPadServiceClient(cc grpc.ClientConnInterface) PadServiceClient {
	return &padServiceClient{cc}
}

func (c *padServiceClient) CreatePad(ctx context.Context, in *CreatePadRequest, opts ...grpc.CallOption) (*CreatedPadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatedPadResponse)
	err := c.cc.Invoke(ctx, PadService_CreatePad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *padServiceClient) GetPad(ctx context.Context, in *PadRequest, opts ...grpc.CallOption) (*PadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PadResponse)
	err := c.cc.Invoke(ctx, PadService_GetPad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *padServiceClient) DeletePad(ctx context.Context, in *PadRequest, opts ...grpc.CallOption) (*PadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PadResponse)
	err := c.cc.Invoke(ctx, PadService_DeletePad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PadServiceServer is the server API for PadService service.
// All implementations must embed UnimplementedPadServiceServer
// for forward compatibility.
//
// PadService defines the gRPC service for managing pads, including creating, retrieving, and deleting pads. Each method corresponds to a specific operation on the pads, allowing clients to interact with the pad management system effectively.
type PadServiceServer interface {
	// CreatePad creates a new pad with the specified content, TTL, and metadata. The response includes the unique ID of the created pad and its status.
	CreatePad(context.Context, *CreatePadRequest) (*CreatedPadResponse, error)
	// GetPad retrieves the content and metadata of a pad by its unique ID. The response includes the pad's body, metadata, and status.
	GetPad(context.Context, *PadRequest) (*PadResponse, error)
	// DeletePad deletes a pad by its unique ID. The response indicates whether the pad was successfully deleted or if it was not found.
	DeletePad(context.Context, *PadRequest) (*PadResponse, error)
	mustEmbedUnimplementedPadServiceServer()
}

// UnimplementedPadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPadServiceServer struct{}

func (UnimplementedPadServiceServer) CreatePad(context.Context, *CreatePadRequest) (*CreatedPadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePad not implemented")
}
func (UnimplementedPadServiceServer) GetPad(context.Context, *PadRequest) (*PadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPad not implemented")
}
func (UnimplementedPadServiceServer) DeletePad(context.Context, *PadRequest) (*PadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePad not implemented")
}
func (UnimplementedPadServiceServer) mustEmbedUnimplementedPadServiceServer() {}
func (UnimplementedPadServiceServer) testEmbeddedByValue()                    {}

// UnsafePadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PadServiceServer will
// result in compilation errors.
type UnsafePadServiceServer interface {
	mustEmbedUnimplementedPadServiceServer()
}

func RegisterPadServiceServer(s grpc.ServiceRegistrar, srv PadServiceServer) {
	// If the following call panics, it indicates UnimplementedPadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PadService_ServiceDesc, srv)
}

func _PadService_CreatePad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PadServiceServer).CreatePad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PadService_CreatePad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PadServiceServer).CreatePad(ctx, req.(*CreatePadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PadService_GetPad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PadServiceServer).GetPad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PadService_GetPad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PadServiceServer).GetPad(ctx, req.(*PadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PadService_DeletePad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PadServiceServer).DeletePad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PadService_DeletePad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PadServiceServer).DeletePad(ctx, req.(*PadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PadService_ServiceDesc is the grpc.ServiceDesc for PadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pad.PadService",
	HandlerType: (*PadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePad",
			Handler:    _PadService_CreatePad_Handler,
		},
		{
			MethodName: "GetPad",
			Handler:    _PadService_GetPad_Handler,
		},
		{
			MethodName: "DeletePad",
			Handler:    _PadService_DeletePad_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pad/proto/pad.proto",
}
