# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      # - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      # - id: no-go-testing
      # - id: golangci-lint
      # - id: go-critic
      - id: go-unit-tests
      - id: go-build
      # - id: go-mod-tidy

  - repo: local
    hooks:
      - id: commitlint
        name: Commit Lint
        entry: commitlint lint --message
        stages: [commit-msg]
        language: system
        description: "Commit Lint to Conventional Commits pattern"
      - id: govulncheck
        name: Go Vulnerability Check
        entry: govulncheck ./...
        stages: [pre-commit]
        language: system
        description: "Go Vulnerability Check"