version: '3'

tasks:
  generate:
    cmds:
      - go get github.com/spf13/cobra/doc@v1.7.0
      - go generate ./...

  prereq:
    cmds:
      - go install -v github.com/go-critic/go-critic/cmd/gocritic@latest
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.1
      - go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - go install golang.org/x/tools/cmd/goimports@latest
