package config

const (
	GSDEV_CONFIGURATION_ENV   = "GSDEV_CONFIGURATION"
	NO_ERROR                  = 0
	ERROR_MISSING_CONF_PATH   = 1
	ERROR_CONF_PATH_NOT_FOUND = 2
	ERROR_CONF_FILE_NOT_FOUND = 3
	ERROR_CONF_FILE_READ      = 4
	ERROR_CONF_FILE_INVALID   = 5
	ERROR_CONF_PATH_IO        = 6
)
