name: Go Release

on:
  release:
    types: [created]

jobs:
  update-report-card:
    name: Update report card
    runs-on: ubuntu-latest
    steps:
      - name: Request to goreportcard.com
        run: curl -s 'https://goreportcard.com/checks' --data-raw 'repo=github.com%2Fguionardo%2Fgs-dev' | jq .
      - name: Read report data
        run: curl -s 'https://goreportcard.com/report/github.com/guionardo/gs-dev' | grep "var response = " | awk -F' ' '{for (i=4; i<NF; i++) printf("%s ", $i)}' > report.json
      - name: Parse JSON
        run: |
          echo "::notice file={report.json},title={Grade}::{$(cat report.json | jq .grade)}
          echo "::notice Grade $(cat report.json | jq .grade)"
          echo "::notice Average $(cat report.json | jq .average)"
          echo "::notice Last Refresh $(cat report.json | jq .last_refresh)"
          echo "::notice Did error $(cat report.json | jq .did_error)"

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.46
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: LICENSE README.md
