name: Go Release

on:
  release:
    types: [created]

jobs:
  update-report-card:
    name: Update report card
    runs-on: ubuntu-latest
    steps:
      - name: Request and extract Report Card
        run: |
          curl -s -o /dev/null  -w '%{http_code}' 'https://goreportcard.com/checks' --data-raw 'repo=github.com%2Fguionardo%2Fgs-dev'
          curl -s 'https://goreportcard.com/report/github.com/guionardo/gs-dev' | grep "var response = " | awk -F' ' '{for (i=4; i<NF; i++) printf("%s ", $i)}' > report.json

      - name: Generate summary
        run: |
          echo "### Resume! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "Grade        $(cat report.json | jq .grade)" >> $GITHUB_STEP_SUMMARY
          echo "Average      $(cat report.json | jq .average)" >> $GITHUB_STEP_SUMMARY
          echo "Last Refresh $(cat report.json | jq .last_refresh)" >> $GITHUB_STEP_SUMMARY
          echo "Did error    $(cat report.json | jq .did_error)" >> $GITHUB_STEP_SUMMARY


  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.46
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: LICENSE README.md docs
